#!/bin/sh

version=v0.1.1

curl https://github.com/winguse/another-dns/releases/download/$version/another-dns-darwin-amd64-$version.gz -L | gzip -d - > /etc/ppp/another-dns
chmod +x /etc/ppp/another-dns

echo ip-up ip-down cn-cidrs.txt static-dns-policy.txt | xargs -n 1 -I {} curl https://wingu.se/static/macos-vpn-scripts/{} -o /etc/ppp/{}

chmod +x /etc/ppp/ip-*
