#!/bin/sh


export PATH=/usr/sbin:/sbin:$PATH


interface=$1
vpn_gateway=$5
regular_gateway=$6

# detect dns polution
probe_dns_ip=43.226.26.107
route add $probe_dns_ip $vpn_gateway
route add 8.8.8.8 $vpn_gateway

cd /etc/ppp

./another-dns \
	--macos \
	-port=53 \
	-vpn-dns=8.8.8.8:53 \
	-vpn-gateway=$vpn_gateway \
	-regular-gateway=$regular_gateway \
	-probe-dns=$probe_dns_ip:8053 > another-dns.log 2>&1 &


